Composer omise php
omise/omise-prestashop pull request #61
Opened 2018-06-26 07:43 UTC by jonrandy

#### 1. Objective

Make it easier to maintain the PrestaShop plugin by pulling in `omise-php` using composer, instead of just having a 'fixed' copy of a particular version of that library stored in the plugin's repo.

#### 2. Description of change

Completely removed the `omise-php` library from the repo, added a `composer.json` file, and modified code so that the path to the now `composer managed` files is correct.

(I also fixed the tests as they were not runnable with recent versions of PHPUnit)

#### 3. Quality assurance

Checked to make sure the plugin still works, which it does

#### 4. Impact of the change

No impact for users as nothing actually changes. Impact is ease of maintenance for devs

#### 5. Priority of change

Normal

#### 6. Additional notes

Calm down England. It was only Panama, it's not like we won the final!

2018-06-26 07:50 UTC, guzzilar commented
@jonrandy how about the installation process?
Right now we guide user to download the repo as a zip file n upload directly into their store.

2018-06-26 07:59 UTC, jonrandy commented
Uploading a zip is the recommended process in PrestaShop. I could write a small shell script to help devs easily produce the required zip file?

2018-06-26 08:00 UTC, jonrandy commented
Unless of course we add the plugin to the PrestaShop 'store'

2018-06-27 04:44 UTC, jonrandy commented
This PR doesn't affect the install process as the ZIP files for the user to download that we add on the releases are manually created by us. They aren't the same as the source code zip file

2018-06-28 06:28 UTC, jonrandy commented
So, is this one ok?

2018-06-28 08:59 UTC, jacekstan commented
I think we need more info in _How to test it.._

2018-06-28 09:12 UTC, jonrandy commented
That would depend on how you wanted to set up your own dev environment. Personally I have a dockerized solution with the relevant plugin folder inside my container pointing at the `omise` folder in my local prestashop dev folder. Then I can run `composer install` to bring in the libs, then test to see if the plugin works as expected

2018-06-30 15:03 UTC, guzzilar commented on .gitignore
> +/omise/vendor
@jonrandy is this should be `vendor/omise`?

2018-06-30 15:04 UTC, guzzilar commented on .gitignore
> +/omise/vendor
ah sry ic, we have `omise` folder at the root dir. 😂

2018-06-30 15:10 UTC, guzzilar requested changes
The changes looks fine.
Just need to update README.md at the Installation Instruction to make it conform with the change.

Also, need to make sure that we have a `built` version after we release for the next version v1.6 (it's ok for now since our document pointed to the released-file. but after we release this one, gotta need to make sure that end-user can install it without running `composer install`)

2018-06-30 16:18 UTC, jonrandy commented
The installation instructions are the same. We have always built the zip,
and that's what they install. This is merely a change to make our
(developers) lives easier

On Sat, 30 Jun 2018, 22:10 Nuttanon Trapnirundon, <notifications@github.com>
wrote:

> *@guzzilar* requested changes on this pull request.
>
> The changes looks fine.
> Just need to update README.md at the Installation Instruction to make it
> conform with the change.
>
> Also, need to make sure that we have a built version after we release for
> the next version v1.4 (it's ok for now since our document pointed to the
> released-file. but after we release this one, gotta need to make sure that
> end-user can install it without running composer install)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/omise/omise-prestashop/pull/61#pullrequestreview-133428473>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABcLMsrYVUybo9m0pSZOfbmwNYDBDVatks5uB5T5gaJpZM4U3aOZ>
> .
>

2018-07-04 08:14 UTC, guzzilar approved these changes
@jonrandy according to
>  The installation instructions are the same. We have always built the zip,

So I guess we need to make a conclusion on where to store that zip file, and update all documents to point to that link instead?

2018-07-04 08:37 UTC, merged